### ISSUE TITLE
[help]: command line argument parser

### ISSUE THREAD

**Issue by hamidb80** [KatrinaKitten/honeycomb#12]
Hey!
I'm confused on writing a "command line argument" parser with `honeycomb`.

here's my code:
```nim
import honeycomb, print

const text = "make global -orient RXY -name vff"

let parser = (
  (many(letter) << whitespace) &
  many((many(c('-') | alphanumeric) << whitespace) & (many(letter) << optional(whitespace))) <<
  eof
)

print parser.parse text
```

----------------------

I was trying to parse a command line input like `make global -orient RXY -name vff` and expected to get something like this:
```nim
["make", "global" , "-orient", "RXY", "-name", "vff"] # or
["make", "global" , @["-orient", "RXY"], @["-name", "vff"]]
```

but I get:
```nim
ParseResult[seq[seq[char]]](
  kind: "success",
  value: @[
    @['m', 'a', 'k', 'e'],
    @['g', 'l', 'o', 'b', 'a', 'l'],
    @['-', 'o', 'r', 'i', 'e', 'n', 't', 'R', 'X', 'Y'],
    @['-', 'n', 'a', 'm', 'e', 'v', 'f', 'f']
  ],
  tail: "",
  fromInput: "make global -orient RXY -name vff"
)
```

I tried to read the tests, but it lacks more advanced examples like this.

**Comment by hamidb80** [comment]
I guess there should be a "add result after previous result" operator like `><`. ( because `&` is not satisfies my need )

**Comment by kgscialdone** [comment]
The `many` function doesn't know you want the characters it's parsing to end up as a string; it only knows how to make `seq`s. You can use the `join` function to coalesce those `seq`s into strings, and the `asSeq` function to wrap as needed so `&` doesn't complain about mismatched result types.

If you'd like some more complex examples than the admittedly limited ones in the documentation site, you can check out the integrations test suite towards the bottom of [tests/tests.nim](https://github.com/KatrinaKitten/honeycomb/blob/master/tests/test.nim#L701).

```nim
import honeycomb, print

const text = "make global -orient RXY -name vff"

let parser = (
  (many(letter).join << whitespace).asSeq &
  many((many(c('-') | alphanumeric).join << whitespace) & (many(letter).join << optional(whitespace))) <<
  eof
)

print parser.parse text
```
```nim
ParseResult[seq[seq[string]]](
  kind: success, 
  value: @[
    @["make"], 
    @["global", ""], 
    @["-orient", "RXY"], 
    @["-name", "vff"]
  ], 
  tail: "", 
  fromInput: "make global -orient RXY -name vff"
)
```

**Comment by hamidb80** [comment]
> If you'd like some more complex examples than the admittedly limited ones in the documentation site, you can check out the integrations test suite towards the bottom of [tests/tests.nim](https://github.com/KatrinaKitten/honeycomb/blob/master/tests/test.nim#L701).

sorry for interruption,
can I use `honeycomb` to parse nested things? [like arrays or objects in JSON]
I couldn't find any examples

**Comment by kgscialdone** [comment]
You absolutely can, while it's not using Honeycomb specifically you can check out the parser I wrote for my language [SeekWhence](https://github.com/KatrinaKitten/SeekWhence/blob/main/src/core/parser.py), which uses a very similar library in Python called [parsy](https://github.com/python-parsy/parsy).
