### ISSUE TITLE
Make honeycomb able to compile for JS

### ISSUE THREAD

**Issue by xigoi** [KatrinaKitten/honeycomb#9]
**Is your feature request related to a problem? Please describe.**
I'd like to compile my library which uses honeycomb to JavaScript, but that's currently not possible because of the dependency on `std/re`.

**Describe the solution you'd like**
Make honeycomb use `std/jsre` instead when compiling to JavaScript.

**Describe alternatives you've considered**
Make the regex functionality optional (since I'm not using it in my library anyway).

**Additional context**
[My library which uses honeycomb](https://git.sr.ht/~xigoi/matext/)

**Comment by kgscialdone** [comment]
There are a few issues with doing so; mainly, Honeycomb uses `re` quite extensively, and `jsre` is not a drop-in replacement. I'll work on this for 0.1.2, but I can't currently guarantee it will be soon.

**Comment by kgscialdone** [comment]
With a little digging (okay, a lot of digging), I managed to create wrapper functions around `jsre` to make it function equivalently to `re` for the handful of functions Honeycomb uses. This is not a long-term solution, and will need to be replaced later, but it should work adequately for now.
